# Generated by Django 3.2.7 on 2023-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbi_django2', '0004_people_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='country',
            field=models.CharField(default=65, max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
