# Generated by Django 3.2.7 on 2023-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbi_django2', '0005_auto_20230728_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='city',
            field=models.CharField(default=34, max_length=30),
        ),
    ]
